Class {
	#name : #OPBPMNNodeType,
	#superclass : #Object,
	#instVars : [
		'type'
	],
	#category : #'OpenPonk-BPMN-Models'
}

{ #category : #'as yet unclassified' }
OPBPMNNodeType class >> Cancel [
	^ #Cancel
]

{ #category : #'as yet unclassified' }
OPBPMNNodeType class >> CatchCompensation [

	^ #CatchCompensation
]

{ #category : #'as yet unclassified' }
OPBPMNNodeType class >> Compensation [

	^ #Compensation
]

{ #category : #'as yet unclassified' }
OPBPMNNodeType class >> CompensationThrow [

	^ #CompensationThrow
]

{ #category : #'as yet unclassified' }
OPBPMNNodeType class >> Complex [
	^ #Complex
]

{ #category : #'as yet unclassified' }
OPBPMNNodeType class >> Conditional [

	^ #Conditional
]

{ #category : #'as yet unclassified' }
OPBPMNNodeType class >> DataInput [
	^#DataInput
]

{ #category : #'as yet unclassified' }
OPBPMNNodeType class >> DataObject [
	^#DataObject
]

{ #category : #'as yet unclassified' }
OPBPMNNodeType class >> DataOutput [
	^#DataOutput
]

{ #category : #'as yet unclassified' }
OPBPMNNodeType class >> DataStore [
	^#DataStore
]

{ #category : #'as yet unclassified' }
OPBPMNNodeType class >> Error [
	^ #Error
]

{ #category : #'as yet unclassified' }
OPBPMNNodeType class >> Escalation [

	^ #Escalation
]

{ #category : #'as yet unclassified' }
OPBPMNNodeType class >> EscalationThrow [

	^ #EscalationThrow
]

{ #category : #'as yet unclassified' }
OPBPMNNodeType class >> Eventbased [
	^ #Eventbased
]

{ #category : #'as yet unclassified' }
OPBPMNNodeType class >> Exclusive [
	^ #Exclusive
]

{ #category : #'as yet unclassified' }
OPBPMNNodeType class >> Inclusive [
	^ #Inclusive
]

{ #category : #'as yet unclassified' }
OPBPMNNodeType class >> Link [
	^ #Link
]

{ #category : #'as yet unclassified' }
OPBPMNNodeType class >> LinkThrow [
	^ #LinkThrow
]

{ #category : #'as yet unclassified' }
OPBPMNNodeType class >> Manual [
	^ #Manual
]

{ #category : #'as yet unclassified' }
OPBPMNNodeType class >> MarkerAdhoc [
	^ #MarkerAdhoc
]

{ #category : #'as yet unclassified' }
OPBPMNNodeType class >> MarkerCompensation [
	^ #MarkerCompensation
]

{ #category : #'as yet unclassified' }
OPBPMNNodeType class >> MarkerLoop [
	^ #MarkerLoop
]

{ #category : #'as yet unclassified' }
OPBPMNNodeType class >> MarkerParallel [
	^ #MarkerParallel
]

{ #category : #'as yet unclassified' }
OPBPMNNodeType class >> MarkerSequential [
	^ #MarkerSequential
]

{ #category : #'as yet unclassified' }
OPBPMNNodeType class >> MarkerSubProcess [	
	^ #MarkerSubProcess
]

{ #category : #'as yet unclassified' }
OPBPMNNodeType class >> Multiple [

	^ #Multiple
]

{ #category : #'as yet unclassified' }
OPBPMNNodeType class >> MultipleThrow [

	^ #MultipleThrow
]

{ #category : #'as yet unclassified' }
OPBPMNNodeType class >> None [
	^ #None
]

{ #category : #'as yet unclassified' }
OPBPMNNodeType class >> Parallel [
	^ #Parallel
]

{ #category : #'as yet unclassified' }
OPBPMNNodeType class >> ParallelMultiple [

	^ #ParallelMultiple
]

{ #category : #'as yet unclassified' }
OPBPMNNodeType class >> Receive [
	^ #Receive
]

{ #category : #'as yet unclassified' }
OPBPMNNodeType class >> Send [

	^ #Send
]

{ #category : #'as yet unclassified' }
OPBPMNNodeType class >> Service [
	^ #Service
]

{ #category : #'as yet unclassified' }
OPBPMNNodeType class >> Signal [

	^ #Signal
]

{ #category : #'as yet unclassified' }
OPBPMNNodeType class >> SignalThrow [

	^ #SignalThrow
]

{ #category : #'as yet unclassified' }
OPBPMNNodeType class >> Terminate [

	^ #Terminate
]

{ #category : #'as yet unclassified' }
OPBPMNNodeType class >> Timer [
	^ #Timer
]

{ #category : #'as yet unclassified' }
OPBPMNNodeType class >> User [
	^#User
]
