"
I store metadata for the OpenPonk-BPMN-Validation package. This package contains the rules, logic, and UI components for validating BPMN models against standard specification constraints.
"
Class {
	#name : 'ManifestOpenPonkBPMNValidation',
	#superclass : 'PackageManifest',
	#category : 'OpenPonk-BPMN-Validation-Manifest',
	#package : 'OpenPonk-BPMN-Validation',
	#tag : 'Manifest'
}

{ #category : 'code-critics' }
ManifestOpenPonkBPMNValidation class >> ruleBadMessageRule2V1FalsePositive [

	<ignoreForCoverage>
	^ #(#(#(#RGPackageDefinition #(#'OpenPonk-BPMN-Validation')) #'2026-07-31T09:51:34.135+02:00') )
]

{ #category : 'code-critics' }
ManifestOpenPonkBPMNValidation class >> ruleUncommonMessageSendRuleV1FalsePositive [

	<ignoreForCoverage>
	^ #(#(#(#RGPackageDefinition #(#'OpenPonk-BPMN-Validation')) #'2026-07-31T09:51:29.308+02:00') )
]
